### ISSUE TITLE
RISCV: Rename device commands

### ISSUE THREAD

**Issue by HanyzPAPU** [d-iii-s/msim#59]
The `csrrd` and `tlbrd` are named after the `rd` command, which stands for "register dump".
In this way `csrrd` would read "control and status register register dump" and `tlbrd` would read "translation look-aside buffer register dump"

I would propose to change these commands to `csrd` and `tlbd`.
This would also be more consistent wrt. the MIPS commands, where the TLB dump is also named `tlbd`.

**Comment by vhotspur** [comment]
> I would propose to change these commands to `csrd` and `tlbd`.

Agreed. I would just like to do this after the course is over and also do it together with #38 and have `csrd` and `cserd` for the extended dump (or something like that).

If you want to work on this, please, feel free to start a draft PR or assign the issue to yourself so that we do not implement it twice :-)

**Comment by HanyzPAPU** [comment]
Could you please assign me to this issue?
It seems cannot do it myself.

I'll create the draft PR when I start working on this issue.
